### ISSUE TITLE
option to have graphs where population start is the "same" year

### ISSUE THREAD

**Issue by matti** [UniversityOfHelsinkiCS/oodikone2-frontend#122]
draws graph so that somebody who has started in 1992 and somebody else who started in 2003 seem to have started in the same year "0"

**Comment by mluukkai** [comment]
This is not relevant with the current populations, but might be useful if we some day have populations consisting of students that started at different time. Currently in staging there is **rage-core**, a population created for testing purposes that is an example of such a population.
