### ISSUE TITLE
population statistics: grade distribution for courses of a population

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#179]
like in tiittanen-excel:

<img width="1148" alt="kuva2" src="https://user-images.githubusercontent.com/523235/41534764-5a5ccd98-7308-11e8-9d18-6bda276da8e4.png">

**Comment by sasumaki** [comment]
- [x] Basic functionality

- [ ] fix all courses not showing
