### ISSUE TITLE
Compulsory courses of study program/population

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#180]
Tasks: 
- [x] add coursetype table and relation to course
- [x] db updater: coursetypes from API
- [x] db updater: typecode for course from API
- [x] return typecode with students for population statistics
- [x] separate endpoint for getting typecodes of courses
- [x] bottlenecksOf should be updated to return the discipines and coursetypecodes for each course object in the result array. 
```
{
   course: {
       code: ...,
       name: ...,
       disciplines: {},
       coursetypes: {}
   } 
   ...
} 
```

Description: 
Could be set manually, or get from backend of https://oprek-www.it.helsinki.fi/

most likely it would be useful to set tags to courses such as

- perusopinto
- aineopinto
- pakollinen
- ...

If known 

- population statistics courses could be tagged (compulsory/not)
- "one click" access to course statistics of all compulsory courses of a study track could be provided

**Comment by ikuisma** [comment]
Oodi API also has "type" -codes for learningopportunities that can be fetched from this endpoint: 
https://oodikone.cs.helsinki.fi/oodi/codes/learningopportunities/types

It contains some of the mentioned "tags" like "aineopinnot" but there is no status code for a compulsory course.
