### ISSUE TITLE
student statistics: in student search start date not shown with new api

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#188]
<img width="1043" alt="kuva" src="https://user-images.githubusercontent.com/523235/41621760-4e0d1e9e-7416-11e8-8b1e-88f3f1752f12.png">

**Comment by totutotu** [comment]
Student university enrollment date is not in the new Oodi api, 'started' date now deleted from the search results table.
