### ISSUE TITLE
separate normal courses from tutkinto/kokonaisuus in backend

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#205]
Currently it is done in many (?) places in front and does not work properly

After some months we'll get the info from DOO-API.

As a intermediate step move all the logic in backend by adding the code here https://github.com/UniversityOfHelsinkiCS/oodikone2-backend/blob/master/src/models/index.js#L103 eg as [getter functions](http://docs.sequelizejs.com/manual/tutorial/models-definition.html#getters-setters)

**Comment by sasumaki** [comment]
Done a bit half-assed
