### ISSUE TITLE
updater: run as cronjob

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#222]
Basic version: Run eg every Friday 23:59 for all students (if it takes less than 2 days) in backend container (_docker exec_). Log progress.

Possible improvements: 

- run in own container (that uses backend image) with _docker run_
- run n hours/students every night, continue next night from where left

**Comment by qzuw** [comment]
Works now, but code may need more error handling (for example api timeouts)
