### ISSUE TITLE
population statistics: study programs with same name

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#227]
these should be separated somehow:

<img width="463" alt="kuva" src="https://user-images.githubusercontent.com/523235/42123598-718a8f06-7c5d-11e8-8090-8e1a581eeb88.png">

**Comment by mluukkai** [comment]
same problem also with lääketiede

a good way to separate would be to include year:

Hamaslääketieteen koulutusohjelma -2016
Hamaslääketieteen koulutusohjelma 2017-

or 

Hamaslääketieteen koulutusohjelma (vanha)
Hamaslääketieteen koulutusohjelma

**Comment by sasumaki** [comment]
Fixed by giving studyright codes
