### ISSUE TITLE
student serch: invalid starting dates

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#230]
The Oodi API contains students who have no studyrights or studyattainments. For this reason we'll avoid adding a heuristic and simply replace the "invalid date" text with something more descriptive.

<img width="690" alt="kuva" src="https://user-images.githubusercontent.com/523235/42123921-b27e6dd4-7c62-11e8-8b5a-f07257a1e38b.png">

**Comment by ikuisma** [comment]
Seems to occur with students who have no studyrights at all.
