### ISSUE TITLE
CourseStatistics: Make backend faster.

### ISSUE THREAD

**Issue by sasumaki** [UniversityOfHelsinkiCS/oodikone2-frontend#285]
It takes approximately 15 seconds to find 2017-2018 statistics of Tietoliikenteen Perusteet...

Make it better!

- [x] Bronze:  < 12.5 sec
- [x] Silver: < 10 sec
- [x] Gold: < 7.5 sec
- [ ] Minttu: < 5 sec

**Comment by totutotu** [comment]
Now faster but still not minttu
