### ISSUE TITLE
/populations/courses?query endpoint should replace codes and names containing "Avoin yo".

### ISSUE THREAD

**Issue by ikuisma** [UniversityOfHelsinkiCS/oodikone2-frontend#299]
The populations courses query returns the first name and code found for a given group of courses. If the name contains "Avoin yo" the name and code should be taken from a course that does not contain  "Avoin yo" in the name.

**Comment by totutotu** [comment]
Implemented to find the most recently held course with exactly the same name without "Avoin yo: " in the beginning
