### ISSUE TITLE
population statistics: datatiede 2017-18 has suspicious graphs

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#466]
![image](https://user-images.githubusercontent.com/523235/46429446-201e4a80-c74f-11e8-891b-be99a21cfafb.png)

**Comment by sasumaki** [comment]
Because of Oodis' faulty `is_leaf` feature. e.g. here the problem is that Bachelor of Science is marked as a course before 2008.
Temporal fix: check if course has at least one `is_leaf: false` study attainment if true mark it as study module.
