### ISSUE TITLE
population statistics: check if update works

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#653]
![image](https://user-images.githubusercontent.com/523235/51511064-7bf90600-1e08-11e9-9230-d29e857d6da5.png)

done several times 21 and 22.1. time stamp does not update

however random sampling shows that in student page the value is correctly updated:

![image](https://user-images.githubusercontent.com/523235/51511126-b1055880-1e08-11e9-85d2-a7f788d6b2eb.png)

for some reason 5 students did not update form lääkis 2017-18, when doing the update from student page, all fine

**Comment by Rochet2** [comment]
manuaalitestattu by tuomo
