### ISSUE TITLE
Token rights are not automatically updated after change in DB

### ISSUE THREAD

**Issue by Rochet2** [UniversityOfHelsinkiCS/oodikone2-frontend#661]
The token is not updated with the new rights.
When you change rights in the userservice database, you must then clear your cache to see those rights. Alternatively you can relog.

When the new update rolls out for userservice, we should have decided if we force everyone to relog or if we somehow update the rights to the token as they are changed.

After talking with mluukkai we decided that it would be best for now to ask for the permissions on every request form the userservice. This allows us to delete any rights at any time and then the user would lose access instead of having access until he relogs.
If performance is a problem later, then a cache can be created to the backend.

Mluukkai suggested adding a middleware that fills the request/token with the new rights from userservice. Caching can then later be built to the middleware as well.

**Comment by sasumaki** [comment]
Could we create "flagged users" where all changed userIds are saved and a middleware that checks if youre flagged and then forces a new token before authorizing anything. After new token the user is removed from flagged users.
