### ISSUE TITLE
Pop stats: Add missing information box to credits table

### ISSUE THREAD

**Issue by totutotu** [UniversityOfHelsinkiCS/oodikone2-frontend#680]
![2018-11-21_credit_accumulation_i](https://user-images.githubusercontent.com/43775188/48836099-7c364000-ed8a-11e8-9d00-6f18cda9826f.JPG)

**Credit accumulation:** Opiskelijoiden kumulatiiviset opintopistekertymät opiskelijakohtaisina kuvaajina. Kun hiiren vie kuvaajien päälle, saa näkyviin jokaista kuvaajaa vastaavan opiskelijanumeron. Opiskelijanumeron yhteydessä olevaa ympyrää klikkaamalla siirtyy ”student statistics” puolelle ja näkee yksittäisen opiskelijan opintotiedot.

X-akselin skaalaa voi säätää harmaista painikkeista ”1m”, ”3m”, ”6m”, ”YTD”, ”1y” ja ”ALL” tai kuvaajan alla olevan sinisen näkymän harmaita ”kahvoja” siirtämällä. Y-akselin skaalaa voi säätää harmaista painikkeista ”small” ”medium” ja "large”

_Originally posted by @tttriple in https://github.com/UniversityOfHelsinkiCS/oodikone2-frontend/issues/538#issuecomment-440617406_

**Comment by Rochet2** [comment]
@totutotu Pitikö tässä tehdäkin jotain? Mulla ainakin näkyy toi teksti jo. ja git blame kertoo että teit sen kuukausi sitten.
