### ISSUE TITLE
Studyright prioritycode to population statistics student list

### ISSUE THREAD

**Issue by ikuisma** [UniversityOfHelsinkiCS/oodikone2-frontend#748]
Add new column to the population statistics  students table with prioritycode of the queried studyright

**Comment by tttriple** [comment]
@ikuisma @mluukkai Sorry to jump in your thread but could we actually add two columns, second one featuring "extent code"? Or maybe the description, like this:

[Student]- ... - [extent code == 1 ] - [prioritycode == 1]

1234567890 - ... - "Alempi korkeakoulututkinto" - "ensisijainen"

That woud be perfect.

Are you able to generate or get similar list of priority codes as you did with extent codes?

1 = ensisijainen
2 = valmistunut
...etc.
