### ISSUE TITLE
Add default filter "have not transferred to" to all study programs.

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/oodikone2-frontend#783]
After population search default filter "have not transferred to" is not *on* for all study programs.

For example: 
"matemaattisten tieteiden kandiohjelma" filter is on
"fysikaalisten tieteiden kandiohjelma" filter is off

This should be fixed for all programs missing the default filter.

**Comment by sasumaki** [comment]
![image](https://user-images.githubusercontent.com/10545809/56135672-e948ad00-5f99-11e9-8e11-e0a515524a48.png)
This is hardcoded feature by @mluukkai 5 months ago. 

Is this something we want?

**Comment by sasumaki** [comment]
This was done because of a request from mathematicians specifically.
At least at CS we don't want this so this will not be implemented elsewhere without a request.
