### ISSUE TITLE
devops: build docker images with travis

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone2-frontend#88]

**Comment by mluukkai** [comment]
https://github.com/UH-StudentServices/kurssisivu-backend/blob/master/.travis.yml

noin luodaan latest-tägätty image jokaisesta testit läpäsevästä commitista

meidän siis pitäisi tehdä 
- jokaisesta commitista staging-tagatty image
- jokaisesta tagatystä commitista latest-tagatty image

**Comment by mluukkai** [comment]
https://github.com/UniversityOfHelsinkiCS/oodikone2-frontend/blob/master/.travis.yml#L17

toimii master -> staging osalta

tag -> latest ei toimi, eli 2 vikaa riviä ei toimi, ts testi väärä

**Comment by sasumaki** [comment]
```
language: node_js
node_js:
- '8'
cache:
  directories:
    - node_modules

sudo: required

services:
  - docker

after_success:
  - "[[ $TRAVIS_BRANCH =~ (master) ]] && docker build -t toska/oodikone2-frontend:staging ."
  - "[[ $TRAVIS_BRANCH =~ (master) ]] && docker login -u $DOCKER_USER -p $DOCKER_PASS"
  - "[[ $TRAVIS_BRANCH =~ (master) ]] && docker push toska/oodikone2-frontend:staging"
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker build -t toska/oodikone2-frontend:latest ."
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker login -u $DOCKER_USER -p $DOCKER_PASS"
  - "[[ $TRAVIS_TAG =~ ([0-1].+) ]] && docker push toska/oodikone2-frontend:latest"
```
Vikalla rivillä ollut " . " ilmeisesti turha/väärin. Onko mahdollista tehdä tagi joka ei käy master branchin kautta? Jos joo niin sillon ei välttämättä oltu kirjauduttu. En oo testannu et onko tuo ylempänä sitten yhtään toimivampi kun en oikeen tiiä miten sitä pitäs testailla räjäyttämättä kaikkea paskaks.
